import random

#list of excuses
list_of_excuses = [
    "My car broke down on the way.",
    "I had a doctor's appointment that ran late.",
    "I lost track of time!",
    "There was a power outage at home.",
    "My alarm didn't go off.",
    "I was stuck in traffic for hours.",
    "I had a family emergency.",
    "My internet was down.",
    "I misplaced my keys.",
    "I was waiting for an important call.",
    "I had to take my pet to the vet unexpectedly.",
    "I got the dates mixed up.",
    "I was feeling under the weather.",
    "There was a water leak in my house.",
    "I had an allergic reaction.",
    "I was locked out of my house.",
    "My babysitter canceled last minute.",
    "I was called into an urgent meeting at work.",
    "I forgot it was due today.",
    "My computer crashed and I lost my work.",
    "I had to help a friend in need.",
    "I was caught in bad weather.",
    "My previous appointment overran.",
    "I thought I had more time to finish it.",
    "I was dealing with a plumbing disaster at home.",
    "The bus was late.",
    "I had to attend a sudden funeral.",
    "I was jury duty ran longer than expected.",
    "I couldn't find parking.",
    "My child was sick.",
    "I had a migraine.",
    "I was waiting for a package that needed a signature.",
    "I had a flat tire.",
    "My phone died and I couldn't check my schedule.",
    "I was dealing with identity theft issues.",
    "I had to sort out a billing error.",
    "I was helping my elderly neighbor.",
    "There was an incident at home I had to take care of.",
    "I was volunteering for a charity event.",
    "I was caught up in a family argument.",
    "I had a severe toothache.",
    "I was updating my software and it took longer than expected.",
    "I had to save a cat stuck in a tree.",
    "I was auditioning for a role in a play.",
    "I was attending a last-minute seminar.",
    "I was waiting for the electrician to fix an issue.",
    "I accidentally went to the wrong location.",
    "I was stuck in an elevator.",
    "I had a lengthy phone call with my bank.",
    "I was writing an important email that I had to send off immediately."
]

#returns n amount of randmon excuses from the list_of_excuses
def get_excuse_list(n):
 return random.sample(list_of_excuses, min(n, len(list_of_excuses)))
